# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Produce605InterbeefFile_main <- function(paramFileName) {
    .Call(`_Produce605InterbeefFile_Produce605InterbeefFile_main`, paramFileName)
}

rcpp_hello <- function() {
    .Call(`_Produce605InterbeefFile_rcpp_hello`)
}

